### ISSUE TITLE
Seems to be cloning repository forever

### ISSUE THREAD

**Issue by crackheadakira** [stirante/facaccimo#1]
I'm trying to make a repository but it just keeps saying **"Cloning Repo"**

**Comment by crackheadakira** [comment]
Fixed it by trying to add the series again but this time selecting existing repo

**Comment by stirante** [comment]
Still, I'm gonna investigate why it does this.

**Comment by stirante** [comment]
Fixed in https://github.com/stirante/facaccimo/commit/f15399e70314a4d9e100ab7bd3887059b87d4dd8

**Comment by stirante** [comment]
@crackheadakira as I side note, I just noticed that all the files in the repo don't have `.json` extension. You might want to add that extension. I will now make an appropriate fix to the app, so it always adds that.

**Comment by stirante** [comment]
I promise this is the last message I'm adding. 
I also added a quick feature that should attempt to fix some files not having `.json` extension.

**Comment by crackheadakira** [comment]
ahh, i didnt realize that i had to manually add the .json extension
