### ISSUE TITLE
The parse reddit post option doesn't seem to be working

### ISSUE THREAD

**Issue by crackheadakira** [stirante/facaccimo#2]
I'm trying to use the Parse Reddit Post option but whenever I try to do it it gives me URL is not a valid Reddit URL. 

This is the URL I'm using https://www.reddit.com/r/MonsterUpscaleProject/comments/nrezx3/monster_vol_1_chapter_2_perfect_edition/

**Comment by stirante** [comment]
Thank you for finding that! I fixed it in https://github.com/stirante/facaccimo/commit/d10081a80f31a9cac76d8d460f74f3212fafc360

I gotta admit, that this whole project was literally a weekend project, so it might contain bugs like these, but it makes me happy, that someone uses it :D

**Comment by crackheadakira** [comment]
this project was a god send for me as i wanted to use cabari.moe and upload a series there but the whole process was kinda hard to understand, and you've thankfully made it so simple, so THANK YOU!
