### ISSUE TITLE
"Error saving series! No anonymous write access!" when trying to save the JSON file.

### ISSUE THREAD

**Issue by crackheadakira** [stirante/facaccimo#27]
Well, there's one additional issue that I'm getting now, and that is `Error saving series! No anonymous write access!` whilst trying to save my edited changes in the JSON file, the error I'm getting in the console this time is
`SmartHttpError: Remote did not reply using the "smart" HTTP protocol. Expected "001e# service=git-upload-pack" but received: No anonymous write access.`

**Comment by stirante** [comment]
Ok, I tested that clone, GitHub API, push and reddit parsing are working. I had to fork cors proxy, that was prepared for git integration and modify it so it allows also requests to other services than reddit.
https://github.com/stirante/cors-proxy
