### ISSUE TITLE
less of issues and more idea's

### ISSUE THREAD

**Issue by crackheadakira** [stirante/facaccimo#4]
I couldn't find a place where I could leave some ideas, so I just made an issues tab

-  I'm wondering if it'd be possible to move the make a new chapter button from the bottom to the top of the section
- Would it be possible to add multi chapter editing, basically allowing you to change multiple chapters volume from 1 to 2 quickly instead of having to manually change each one.

**Comment by stirante** [comment]
First one is easy, will do tomorrow.

Second one might require some custom UI for that, but still seems doable as long as the only thing you change is volume and *maybe* group name. multi title editing seems a bit useless, but still possible.

**Comment by stirante** [comment]
Both done :D
