### ISSUE TITLE
another feature request

### ISSUE THREAD

**Issue by crackheadakira** [stirante/facaccimo#5]
Would it be possible to add a button like the "Parse Reddit Post" but instead it turns Google Drive Share Links into Direct Image Links.

Here's an example.
This here is the original link. https://drive.google.com/file/d/1CXl2_pVntX76UbNAgI_jo_VpU6i1WWdt/view?usp=sharing
This here is the result we want to get. https://drive.google.com/uc?export=view&id=1CXl2_pVntX76UbNAgI_jo_VpU6i1WWdt

You can get this link by copying the Image ID which is the random characters between /d/ and /view
For this example the image ID is **1CXl2_pVntX76UbNAgI_jo_VpU6i1WWdt**
To get the clickable image you put the Image ID after the **id=** `https://drive.google.com/uc?export=view&id=`

**Comment by stirante** [comment]
I grouped all import options (reddit parsing and google drive parsing) to a dropdown menu and added custom import modal.

Also now this import option will append image URLs to existing ones instead of replacing all of them.
