### ISSUE TITLE
i cannot login

### ISSUE THREAD

**Issue by unableunreality** [stirante/facaccimo#57]
please, i can't log in.. your link can't response : https://stirante.com/facaccimo/

**Comment by stirante** [comment]
The server was temporarily unavailable. Everything works again

**Comment by unableunreality** [comment]
i can't log in.. againn..

**Comment by stirante** [comment]
Just published the first version of desktop wrapper. Now you can download it and use it locally. The online version will still be updated, but in case it's down, you can use desktop one.

https://github.com/stirante/facaccimo/releases/tag/1.0.0
