### ISSUE TITLE
X.5 chapter always at the end

### ISSUE THREAD

**Issue by Skytowz** [stirante/facaccimo#61]
The bonus chapter like "15.5" are stuck at the end of the list, and when we want to add an other entry it takes always the information of this chapter, so if we are at chapter 30 and we want to add a new chapter it's gonna propose the chapter 16.5, and it's a little annoying :/

**Comment by SeanR-ScanR** [comment]
Thanks, but it's seems that now we can't navigate through an other page than the 1st one

**Comment by Skytowz** [comment]
(Oups sorry wrong account)

**Comment by stirante** [comment]
Hey, I couldn't reproduce the error. Switching pages seems to be working just fine.

**Comment by Skytowz** [comment]
Yes, don't know why, yesterday I couldn't do it but this morning it was working juste fine, maybe cache error ? don't know
