### ISSUE TITLE
Add new chapter always show chapter 2

### ISSUE THREAD

**Issue by Skytowz** [stirante/facaccimo#62]
Hello, 
When I'm trying to add a new chapter it's always proposing "2" (in the case where the first chapter of the gist is 1, in other case it's <minimum chapter>+1), I think's it may have broke with the fix for chapters sorting.

And another point, I can't change the sorting of the list manually, the arrow changes direction but Nothing Happen (I'm on a Chromium Browser, don't now if it have something to do with it), I can open another issue for this if you want.

**Comment by stirante** [comment]
New chapter number fixed in https://github.com/stirante/facaccimo/commit/a82cd15e4b7572d982b7c2c9ff746e799bfb6f6e

Yes, sorting seems to be broken and I cannot find out why. I tried rolling back the code to the last working version and it still doesn't work. Super weird.

**Comment by Skytowz** [comment]
Thanks !

The sorting never work for me, but it's not really a big problem I think, so I never came here to do an issue, I just took the opportunity to say it now, because it's a little related (Sorry for my poor english btw, not my native language)
