### ISSUE TITLE
[Req] Support Intermediate Chapters

### ISSUE THREAD

**Issue by BrutuZ** [stirante/facaccimo#9]
Instead of limiting the chapter numbers to integers, make it a float so we can add extra content such as Omakes "between" chapters numbering them #.#
 - Ch. 1 - Begin
 - Ch. 1.5 - [Omake]
 - Ch. 2 - The Plot Thickens
 - Ch. 3 - The End

Cubari does support this numbering scheme

**Comment by stirante** [comment]
Done in https://github.com/stirante/facaccimo/commit/15fe606549eecad12d01449e94f1fd70b9f955d3

Live version already updated.
